logging:
  config: ${HOME}/Projekte/netflix-mock/logging.conf

server:
  port: 8000
  log_level: debug  # critical, error, warning, info, debug, trace
  upload_dir: ${HOME}/Projekte/netflix-mock/upload

database:
  # url: "sqlite+pysqlite:///:memory:"
  # url: sqlite:///test-db.db
  # url: sqlite:///..\\test-db.db
  url: sqlite:///${HOME}/Projekte/netflix-mock/test-db.db
  # url: postgresql://test:test@localhost/test.db
  logging: true

api:
  username: ${MOCK_USERNAME}  # basic auth
  password: ${MOCK_PASSWORD}  # basic auth
  spec: ${HOME}/Projekte/netflix-mock/er-if.json

admin:
  username: ${ADMIN_USERNAME} # basic auth to change settings
  password: ${ADMIN_USERNAME} # basic auth to change settings
